
packet:
  logging: false
stats:
  maxHitPoints: 100
  maxStamina: 100
  maxMana: 100
server:
  name: JUOServer
  host: localhost
  port: 7775
combat:
  dexAttackDivisorModifier: 5
  strAttackDivisorModifier: 2
  dexDefenseDivisorModifier: 5
  strDefenseDivisorModifier: 2
command:
  activationChar: .