# Balron
- templateId: 0x1
  name: Balron
  modelId: 0xA
  strength: 100
  dexterity: 100
  intelligence: 100
  maxHitPoints: 100
  maxStamina: 100
  maxMana: 100
  notoriety: Murderer
  hue: 0x83EA

# Skeleton
- templateId: 0x2
  name: Skeleton
  #aiScript: net.sf.juoserver.model.ai.WalkScript
  modelId: 0x93
  strength: 100
  dexterity: 100
  intelligence: 100
  maxHitPoints: 100
  maxStamina: 100
  maxMana: 100
  notoriety: Murderer
  hue: 0x83EA

# Ogre
- templateId: 0x3
  name: Ogre
  #aiScript: net.sf.juoserver.model.ai.WalkScript
  modelId: 0x1
  strength: 100
  dexterity: 100
  intelligence: 100
  maxHitPoints: 100
  maxStamina: 100
  maxMana: 100
  notoriety: Murderer
  hue: 0x83EA

# Ogre
- templateId: 0x4
  name: Balrog
  #aiScript: net.sf.juoserver.model.ai.WalkScript
  modelId: 0x11c
  strength: 100
  dexterity: 100
  intelligence: 100
  maxHitPoints: 100
  maxStamina: 100
  maxMana: 100
  notoriety: Murderer
  hue: 0x83EA