name: CICD for push any branch
on:
  push:
    branches:  ["**"]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compiling the Code
        run: ./gradlew clean build